---
name: Music-Chord-Note
version: 0.0.6
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
abstract: get Chord Tone List from Chord Name
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Test::More: 0
provides:
  Music::Chord::Note:
    file: lib/Music/Chord/Note.pm
    version: 0.0.6
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
